
//ERRORS
export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

//CURRENT USER
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

//MESSAGES
export const FETCHING_MESSAGES = "FETCHING_MESSAGES";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const POST_MESSAGE = "POST_MESSAGE";
export const ANIMATE_REMOVE_MESSAGE = "ANIMATE_REMOVE_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const LIKE_MESSAGE = "LIKE_MESSAGE";
export const UPDATE_MESSAGES = "UPDATE_MESSAGES";
export const LAST_MESSAGE = "LAST_MESSAGE";
export const LOAD_MSG_LIKES ="LOAD_MSG_LIKES";
export const UPDATE_LIKE_LIST = "UPDATE_LIKE_LIST";

//USER PROFILE
export const FETCHING_PROFILE = "FETCHING_PROFILE";
export const LOAD_USER_PROFILE = "LOAD_USER_PROFILE";
export const LOAD_USER_FOLLOW = "LOAD_USER_FOLLOW";
export const UPDATE_USER_PROFILE ="UPDATE_USER_PROFILE";

//FOLLOW INFO
export const UPDATE_FOLLOW_LIST = "UPDATE_FOLLOW_LIST";
export const CLEAR_FOLLOW = "CLEAR_FOLLOW";

//ANIMATIONS
export const ANIMATE_ENTER = "ANIMATE_ENTER";
export const ANIMATE_ENTER_REVERSE = "ANIMATE_ENTER_REVERSE";
export const ANIMATE_EXIT = "ANIMATE_EXIT";
export const ANIMATE_EXIT_REVERSE = "ANIMATE_EXIT_REVERSE";
export const ANIMATE_REMOVE = "ANIMATE_REMOVE";
export const ANIMATE_PROFILE = "ANIMATE_PROFILE";

//OTHER UI
export const SHOW_FOLLOW = "SHOW_FOLLOW";
export const CLOSE_FOLLOW = "CLOSE_FOLLOW";
export const SHOW_LIKES = "SHOW_LIKES";
export const CLOSE_LIKES = "CLOSE_LIKES";
export const SHOW_NEW_MESSAGE = "SHOW_NEW_MESSAGE";
export const CLEAR_ALL = "CLEAR_ALL";
export const GET_DISCOVER_USERS = "GET_DISCOVER_USERS";
export const ANIMATE_CLOSE = "ANIMATE_CLOSE";
export const IS_LOADING = "IS_LOADING";
export const IS_LOADED = "IS_LOADED";
export const WINDOW_RESIZE = "WINDOW_RESIZE";
export const SET_CONTEXT="SET_CONTEXT";
export const SHOW_SIDEBAR = "SHOW_SIDEBAR";
export const HIDE_SIDEBAR = "HIDE_SIDEBAR";
export const EDIT_PROFILE_PAGE = "EDIT_PROFILE_PAGE";
